
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Implements a Genkit flow for detecting hidden narratives in text using a 'paranoid reading' approach.
 *
 * - detectHiddenNarratives - The main function to initiate the hidden narrative detection flow.
 * - DetectHiddenNarrativesInput - The input type for the detectHiddenNarratives function.
 * - DetectHiddenNarrativesOutput - The output type for the detectHiddenNarratives function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectHiddenNarrativesInputSchema = z.object({
  text: z.string().describe('The text to analyze for hidden narratives.'),
});
export type DetectHiddenNarrativesInput = z.infer<typeof DetectHiddenNarrativesInputSchema>;

const DetectHiddenNarrativesOutputSchema = z.object({
  hiddenNarratives: z
    .string()
    .describe('The detailed hidden narratives detected in the text, from a paranoid perspective, presented in a comprehensive manner.'),
});
export type DetectHiddenNarrativesOutput = z.infer<typeof DetectHiddenNarrativesOutputSchema>;

export async function detectHiddenNarratives(input: DetectHiddenNarrativesInput): Promise<DetectHiddenNarrativesOutput> {
  return detectHiddenNarrativesFlow(input);
}

const detectHiddenNarrativesPrompt = ai.definePrompt({
  name: 'detectHiddenNarrativesPrompt',
  input: {schema: DetectHiddenNarrativesInputSchema},
  output: {schema: DetectHiddenNarrativesOutputSchema},
  prompt: `You are tasked with performing a "paranoid reading" of the following text to uncover implicit intentions and hidden narratives.

  Text: {{{text}}}

  Analyze the text from a perspective that assumes there are hidden meanings, agendas, and potential manipulations at play. Identify any underlying narratives or intentions that are not explicitly stated but may be implied through the language used, the context provided, or the subtext detectable through careful scrutiny.

  Present your findings as a detailed and comprehensive report of the detected hidden narratives. Ensure your report is thorough and well-explained.
  `,
});

const detectHiddenNarrativesFlow = ai.defineFlow(
  {
    name: 'detectHiddenNarrativesFlow',
    inputSchema: DetectHiddenNarrativesInputSchema,
    outputSchema: DetectHiddenNarrativesOutputSchema,
  },
  async input => {
    const {output} = await detectHiddenNarrativesPrompt(input);
    return output!;
  }
);
