
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Implements a Genkit flow for detecting hidden narratives in text using a 'paranoid reading' approach.
 *
 * - detectHiddenNarratives - The main function to initiate the hidden narrative detection flow.
 * - DetectHiddenNarrativesInput - The input type for the detectHiddenNarratives function.
 * - DetectHiddenNarrativesOutput - The output type for the detectHiddenNarratives function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectHiddenNarrativesInputSchema = z.object({
  text: z.string().describe('The text to analyze for hidden narratives.'),
  language: z.string().default('fr').describe('The language for the response (e.g., "fr", "en").'),
});
export type DetectHiddenNarrativesInput = z.infer<typeof DetectHiddenNarrativesInputSchema>;

const DetectHiddenNarrativesOutputSchema = z.object({
  hiddenNarratives: z
    .string()
    .describe('The detailed, comprehensive, and substantial hidden narratives detected in the text, from a paranoid perspective, presented in a well-explained manner.'),
});
export type DetectHiddenNarrativesOutput = z.infer<typeof DetectHiddenNarrativesOutputSchema>;

export async function detectHiddenNarratives(input: DetectHiddenNarrativesInput): Promise<DetectHiddenNarrativesOutput> {
  return detectHiddenNarrativesFlow(input);
}

const detectHiddenNarrativesPrompt = ai.definePrompt({
  name: 'detectHiddenNarrativesPrompt',
  input: {schema: DetectHiddenNarrativesInputSchema},
  output: {schema: DetectHiddenNarrativesOutputSchema},
  prompt: `You are tasked with performing a "paranoid reading" of the following text to uncover implicit intentions and hidden narratives.
  Your response should be in {{language}}.

  Text: {{{text}}}

  Analyze the text from a perspective that assumes there are hidden meanings, agendas, and potential manipulations at play. Identify any underlying narratives or intentions that are not explicitly stated but may be implied through the language used, the context provided, or the subtext detectable through careful scrutiny.

  Present your findings as a detailed, comprehensive, and substantial report of the detected hidden narratives. 
  IMPORTANT: Your response should be as long, detailed, comprehensive, and substantial as possible, exploring all facets of the request. Do not summarize or truncate your thoughts prematurely. Aim for maximum token utilization to provide the deepest possible analysis.
  Ensure your report is thorough, well-explained, and provides significant depth.
  `,
});

const detectHiddenNarrativesFlow = ai.defineFlow(
  {
    name: 'detectHiddenNarrativesFlow',
    inputSchema: DetectHiddenNarrativesInputSchema,
    outputSchema: DetectHiddenNarrativesOutputSchema,
  },
  async input => {
    try {
        const {output} = await detectHiddenNarrativesPrompt(input);
        return output!;
    } catch (error) {
        console.error("Error in detectHiddenNarrativesFlow:", error);
        const lang = input.language || 'fr';
        const errorMessage = lang === 'fr' 
            ? "Échec de la détection des narratifs cachés." 
            : "Failed to detect hidden narratives.";
        return { hiddenNarratives: errorMessage };
    }
  }
);
    
